;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="AI",DevComment="AI tags for state tree and other functionalities")
+GameplayTagList=(Tag="AI.Perception",DevComment="")
+GameplayTagList=(Tag="AI.Perception.OnLostSight",DevComment="")
+GameplayTagList=(Tag="AI.Perception.OnSight",DevComment="")
+GameplayTagList=(Tag="Audio",DevComment="Tags For audio managers")
+GameplayTagList=(Tag="Audio.Music.Combat",DevComment="")
+GameplayTagList=(Tag="Audio.Music.Menu",DevComment="")

